name: Check
on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔎 Lint
        run: pnpm run lint

      - name: 🔎 Check formatting
        run: pnpm run format:check

      - name: 🚨 Run unit tests
        run: pnpm run test:unit

      - name: 🛠️ Build
        run: pnpm run build

      # install system dependencies for Playwright
      # see: https://playwright.dev/python/docs/browsers#install-system-dependencies
      - name: 📦 Install Playwright system dependencies
        run: pnpm exec playwright install-deps

      - name: 🧪 Run Playwright tests
        run: pnpm run test:e2e
